name: Build and Deploy

on:
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: deployment-action
      # - name: Install NPM dependencies
      #   run: npm install
      # - name: build
      #   run: npm run build-storybook
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
      - name: Push to gh-pages
        run: |
          git branch --show-current
          git push origin HEAD:dummy
